Jf email
notificus/notification-service pull request #3
Opened 2018-10-19 17:43 UTC by JacobFontaine

2018-10-19 19:19 UTC, pgarneau requested changes

2018-10-19 19:19 UTC, pgarneau commented on src/main/java/notification/Email.java
> +package notification;
J'ajouterais maybe un package "service" pour ensuite avoir un autre package "email". Dans ca, t'aurais une interface pour ton EmailService avec send() et create(). Pis la version email serait un implementation de cette interface la. Si on decide d'ajouter des nouvelles facons d'envoyer du stock, on va pouvoir reuse.

2018-10-19 19:19 UTC, pgarneau commented on src/test/java/notification/EmailTest.java
> +
Tu pourrais ajouter des tests pour tes exceptions. Aussi what if le create a fail? Tu test pas le assertFalse.

2018-10-19 19:19 UTC, pgarneau commented on src/main/java/notification/Email.java
> +        {
Get that C/C++ shit outa here :P

2018-10-19 19:19 UTC, pgarneau commented on src/main/java/notification/Email.java
> +    }
Generalement tu vas mettre 1-2 espaces entre tes methodes

2018-10-19 19:19 UTC, pgarneau commented on src/main/java/notification/Email.java
> +            final String toEmail = destination;
ya une raison pour faire ca?

2018-10-19 19:19 UTC, pgarneau commented on src/test/java/notification/EmailTest.java
> +    public void testSendEmailSuccess() {
Nom de fonction de test: "sendEmailWhenEverythingCorrectThenSuccessful"

2018-10-20 19:33 UTC, boscoa commented on src/main/java/notification/Email.java
> +        if(createEmail(session,subject,content, destination))
Tu pourrais return directement le résultat de createEmail au lieu du if/else

2018-10-20 19:36 UTC, boscoa requested changes

2018-10-20 19:36 UTC, boscoa commented on src/main/java/notification/Email.java
> +        if(createEmail(session,subject,content, destination))
Tu pourrais return le résultat de createEmail à la place du if/else

2018-10-21 13:48 UTC, pgarneau approved these changes

2018-10-21 22:17 UTC, boscoa approved these changes

2018-10-22 00:34 UTC, merged